name: getx_module
description: "Help Applying GetX in Flutter"
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/getx_module

version: 1.0.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  june_flow_util:
  get: #@add

dev_dependencies:
  flutter_test:
    sdk: flutter

  widget_binding_module: #@add

flutter:
  assets:
    - assets/module/getx_module/
  uses-material-design: true